### ISSUE TITLE
Suggestions on README.md

### ISSUE THREAD

**Issue by kalantar** [pdettori/kealm#7]
After installing several times, here is some feedback on the README

- Move the instructions to create a new virtual hub context to after the creation of the virtual hub and before the creation of `cluster1`.  This is needed to run the `clusteradm accept` command. 
- I see the `clusteradm accept` command twice. Once before the creation of the virtual hub context and once after. Remove from before.
- Instead of saying "log onto ... cluster", it would be clearer to say "change context to the ... cluster": `kubectl config use-context ...`
- Be explicit about context instead of relying on side effects of previous commands. Before `clusteradm join ...` explictly indicate to use the context of the newly created cluster.

**Comment by pdettori** [comment]
This was addressed in https://github.com/pdettori/kealm/pull/8
